language: python
cache: pip
python:
  - "3.7"
services:
  - postgresql
addns:
  postgresql: "9.5"
install: "pip install -r requirements.test.txt ."
before_script:
  - psql -c 'create database wanmap_test;' -U postgres
  - initialize_wanmap_db test.ini
script: pytest
